

<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Quote Form',
            'trigger': '[data-trigger=trigger]',
            'responsive': true
            
        }}">



    <div class="content">
         <form name="quote_form" method="post" action="<?php echo $this->getUrl('quote/index/save', ['_secure' => true]);?>">
                <div class="form-group">
                  <label for="firstname"> Name :</label>
                  <input type="text"
                  value="<?php echo $block->getCustomerName(); ?>" 
                   name='name' class="form-control" id="firstname" placeholder="Enter First Name" required>
                </div>


                <div class="form-group">
                  <label for="email">Email:</label>
                  <input type="email" value="<?php echo $block->getCustomerEmail(); ?>" name="email" class="form-control" id="email" placeholder="Enter email"required/>
                </div>

                

                <div class="form-group">
                  <label for="productname">Product Name:</label>
                  <input type="text" name="product_name" value="<?php echo $block->getProductName(); ?>" class="form-control" id="productname" required/>
                </div>
                <div class="form-group">
                
                  <input type="hidden" name="product_price" value="<?php echo $block->getProductPrice()?>" class="form-control" id="productprice"/>
                </div>

                

                <div class="form-group">
                  <label for="note">Comment:</label>
                  <textarea id="note" name="quote_text" class="form-control" rows="5" required></textarea>
                     
                </div>

                <button type="submit" class="action primary tocart">Place Request</button>
            </form>
    </div>

 


</div>

<button type="button" class="action primary tocart" data-trigger="trigger">
    <span><?= $block->escapeHtml("Send a Quote") ?></span>
</button>  